### PR TITLE
Always output all errors instead of stopping after the first error

### PR DESCRIPTION
**Pull request by jyn514**
@martin-t can you confirm that this fixes your issue with non-deterministic output? I can't reproduce your issue locally.

Hopefully closes https://github.com/deadlinks/cargo-deadlinks/issues/56.

### CODE REVIEW

**Comment by martin-t** [comment]
This prints a lot more but i still get different results on different computers.

I also noticed now it prints broken links *within a single file* in a different order each time - not sure it used to do that.

I don't have more time to look into this now, i'll try to come back to it and see what exactly the differences are.

This MR definitely improves the situation though - might be worth merging now but keeping the issue open.

**Comment by jyn514** [comment]
> This prints a lot more but i still get different results on different computers.

Parallelism/non-determinism in the files ordering is expected, I can make that an optional feature though. When you say different results, do you mean it's not always catching everything? Or just that it's in a non-deterministic order?

> I also noticed now it prints broken links within a single file in a different order each time - not sure it used to do that.

That's strange ... the only parallelism is on the files themselves, not within a file (AFAIK). Unless `Handle.children.iter()` returns things in a random order? I don't know what deadlinks could do about that if so - maybe I could sort the output before printing it?

**Comment by jyn514** [comment]
I managed to reproduce the original issue on master (I was on the wrong commit before 🤦) and it does seem to be fixed with this branch. This has no output for me with the changes from this MR:
```
$ cargo deadlinks 2>a.txt
$ cargo deadlinks 2>b.txt
$ sort a.txt | diff - <(sort b.txt)
```
Can you try it locally and make sure the only thing different is the ordering? Non-determinism in the ordering doesn't seem exactly a bug to me, just a future enhancement.

**Comment by martin-t** [comment]
Alright, i finally did a proper experiment starting from a clean state:

```
rustup update stable

git clone git@github.com:amethyst/legion.git
cd legion
cargo doc  # warns about collisions
cd ..

git clone git@github.com:jyn514/cargo-deadlinks.git
cd cargo-deadlinks
git checkout deterministic
cargo build
./target/debug/cargo-deadlinks deadlinks ../legion/
```

This finds the same broken links on both computers (though in a different order on each and between runs).

Exact results:
My desktop first run: https://gist.github.com/martin-t/1580f86d339c17a8418e2f8df65bfa85
My desktop second run: https://gist.github.com/martin-t/6642271aabf634e395e0b8664e058111
My laptop first run: https://gist.github.com/martin-t/955c63e6b3b7a56f098ef5a972bfbb33
My laptop second run: https://gist.github.com/martin-t/2c199a910edacdc42817952f3c455c4c

Observations:
- The broken links found on each run are the same.
- Files are reported in a similar order between runs on the same machine but vary between machines.
- Broken links within a file very between runs.

The different order is probably not an issue for normal use, though it might make automated testing of cargo-dealinks itself harder.

The important thing is that it seems to find all broken links now. The nondeterministic order and the fact that it used to quit after the first file explain why #56 happened which is fixed now.

I also realized why i probably got different results on each machine (one gave me about twice the number of broken links) - i cloned/updated and compiled legion on each at a different time which means even though the version of legion itself during the test was the same, each likely had slightly different versions of deps as long as they were semver compatible. Given deadlinks finds broken links of deps too, those were probably the difference (just harder to notice in the noise because of the different orders). If you wanna run the above commands for yourself, you might also wanna disable things like sccache in case it affects how dep versions are resolved (it shouldn't given Cargo.lock exists but who knows).

**Comment by jyn514** [comment]
Got it, that makes sense. I'll open a new issue for deterministic output within a file.

**Pull request merged**
